title: "Question Generation Taxonomy"
description: "GitHub Pages site for QG taxonomy with TOC"
theme: jekyll-theme-cayman

# Optional niceties that GitHub Pages allows
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO tag defaults (safe even if plugin not enabled)
defaults:
  - scope:
      path: ""
    values:
      layout: default

